# Generated by Django 3.1.7 on 2021-06-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255)),
                ('subscription_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Stripe Customers',
            },
        ),
    ]
