# Generated by Django 3.1.7 on 2021-06-14 03:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_type', models.CharField(choices=[('Artistic Endeavors', 'Artistic Endeavors'), ('Community Service/Volunteer - Medical/Clinical', 'Community Service/Volunteer - Medical/Clinical'), ('Community Service/Volunteer - Not Medical/Clinical', 'Community Service/Volunteer - Not Medical/Clinical'), ('Conferences Attended', 'Conferences Attended'), ('Extracurricular Activities', 'Extracurricular Activities'), ('Hobbies', 'Hobbies'), ('Honors/Awards/Recognitions', 'Honors/Awards/Recognitions'), ('Intercollegiate Athletics', 'Intercollegiate Athletics'), ('Leadership - Not Listed Elsewhere', 'Leadership - Not Listed Elsewhere'), ('Military Service', 'Military Service'), ('Other', 'Other'), ('Paid Employment - Medical/Clinical', 'Paid Employment - Medical/Clinical'), ('Paid Employment - Not Medical/Clinical', 'Paid Employment - Not Medical/Clinical'), ('Physician Shadowing/Clinical Observation', 'Physician Shadowing/Clinical Observation'), ('Presentations/Posters', 'Presentations/Posters'), ('Publications', 'Publications'), ('Research/Lab', 'Research/Lab'), ('Teaching/Tutoring/Teaching Assistant', 'Teaching/Tutoring/Teaching Assistant')], max_length=50)),
                ('experience_name', models.CharField(max_length=100)),
                ('organization_name', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=10)),
                ('end_date', models.CharField(blank=True, max_length=10)),
                ('total_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('repeated', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('contact_first_name', models.CharField(blank=True, max_length=50)),
                ('contact_last_name', models.CharField(blank=True, max_length=50)),
                ('contact_title', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('experience_description', models.TextField(blank=True, max_length=700)),
                ('most_meaningful', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('most_meaningful_summary', models.TextField(blank=True, max_length=1325)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
    ]
