# Generated by Django 3.1.7 on 2021-06-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_title', models.CharField(max_length=200)),
                ('letter_type', models.CharField(max_length=200)),
                ('school_association', models.CharField(blank=True, max_length=200)),
                ('author_prefix', models.CharField(blank=True, max_length=200)),
                ('author_first_name', models.CharField(max_length=200)),
                ('author_last_name', models.CharField(max_length=200)),
                ('author_title', models.CharField(blank=True, max_length=200)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
