# Generated by Django 3.1.7 on 2021-05-28 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('due_date', models.CharField(blank=True, max_length=200)),
                ('priority', models.CharField(blank=True, choices=[('Urgent', 'Urgent'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=200)),
                ('completed', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20)),
                ('tag', models.CharField(blank=True, choices=[('Activities', 'Activities'), ('Coursework', 'Coursework'), ('Letters', 'Letters'), ('MCAT', 'MCAT'), ('Other', 'Other')], max_length=20)),
                ('tray', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
