# Generated by Django 3.1.7 on 2021-05-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, choices=[('2021-2022', '2021-2022'), ('2020-2021', '2020-2021'), ('2019-2020', '2019-2020'), ('2018-2019', '2018-2019'), ('2017-2018', '2017-2018'), ('2016-2017', '2016-2017'), ('2015-2016', '2015-2016'), ('2014-2015', '2014-2015'), ('2013-2014', '2013-2014'), ('2012-2013', '2012-2013'), ('2011-2012', '2011-2012')], max_length=200)),
                ('academic_term', models.CharField(blank=True, choices=[('Summer Semseter (Summer)', 'Summer Semseter (Summer)'), ('First Semester (Fall)', 'First Semester (Fall)'), ('2nd Semester (Spring)', '2nd Semester (Spring)'), ('Mini Semester (Winter/Spring)', 'Mini Semester (Winter/Spring)'), ('Full Year Course - Semester System', 'FullYear Course - Semester System'), ('Summer Quarter (Summer)', 'Summer Quarter (Summer)'), ('1st Quarter (Fall)', '1st Quarter (Fall)'), ('2nd Quarter (Winter)', '2nd Quarter (Winter)'), ('3rd Quarter (Spring)', '3rd Quarter (Spring)'), ('Full Year Course - Qaurter System', 'FullYear Course - Qaurter System'), ('Summer Trimester (Summer)', 'Summer Trimester (Summer)'), ('1st Trimester (Fall)', '1st Trimester (Fall)'), ('2nd Trimester (Winter)', '2nd Trimester (Winter)'), ('3rd Trimester (Spring)', '3rd Trimester (Spring)'), ('FullYear Course - Trimester System', 'FullYear Course - Trimester System'), ('Summer Semester (Summer)', 'Summer Semester (Summer)'), ('1st Semester (Fall)', '1st Semester (Fall)'), ('2nd Semester (Spring)', '2nd Semester (Spring)'), ('Mini Semester (Winter/Spring)', 'Mini Semester (Winter/Spring)'), ('Full Year Course - 4-1-4 / 4-4-1 System', 'Full Year Course - 4-1-4 / 4-4-1 System'), ('Other Term', 'Other Term')], max_length=200)),
                ('school_year', models.CharField(blank=True, choices=[('High School', 'High School'), ('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Postbaccalaureate Undergraduate', 'Postbaccalaureate Undergraduate'), ('Graduate', 'Gradutae')], max_length=200)),
                ('course_number', models.PositiveIntegerField(blank=True, null=True)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_classification', models.CharField(blank=True, choices=[('Behavioral & Social Sciences', 'Behavioral & Social Sciences'), ('Biology', 'Biology'), ('Business', 'Business'), ('Chemistry', 'Chemistry'), ('Communications', 'Communications'), ('Computer Science/Technology', 'Computer Science/Technology'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('English Language & Literature', 'English Language & Literature'), ('Fine Arts', 'Fine Arts'), ('Foreign Languages & Literature', 'Foreign Languages & Literature'), ('Government/Political Science/Law', 'Government/Political Science/Law'), ('Health Sciences', 'Health Sciences'), ('History', 'History'), ('Math', 'Math'), ('Natural/Physical Sciences', 'Natural/Physical Sciences'), ('Other', 'Other'), ('Philosophy/Religion', 'Philosophy/Religion'), ('Physics', 'Physics'), ('Special Studies', 'Special Studies')], max_length=200)),
                ('credit_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('transcript_grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('AB', 'AB'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('BC', 'BC'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('CD', 'CD'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('DE', 'DE'), ('F', 'F')], max_length=200, null=True)),
                ('include_lab', models.CharField(blank=True, choices=[('Lecture Only', 'Lecture Only'), ('Lab Only', 'Lab Only'), ('Combined Lecture and Lab', 'Combined Lecture and Lab')], max_length=200)),
            ],
            options={
                'verbose_name_plural': 'coursework',
            },
        ),
    ]
