# Generated by Django 3.1.7 on 2021-06-14 03:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.CharField(max_length=10)),
                ('test_company', models.CharField(choices=[('AAMC', 'AAMC'), ('Altius', 'Altius'), ('Blueprint', 'Blueprint'), ('Gold Standard', 'Gold Standard'), ('Kaplan', 'Kaplan'), ('Magoosh', 'Magoosh'), ('McGraw Hill', 'McGraw Hill'), ('The Princeton Review', 'The Princeton Review'), ('Other', 'Other')], max_length=20)),
                ('test_type', models.CharField(choices=[('Official', 'Official'), ('Practice', 'Practice')], max_length=8)),
                ('test_name', models.CharField(blank=True, max_length=80)),
                ('bio_biochem', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(118), django.core.validators.MaxValueValidator(132)])),
                ('chem_physics', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(118), django.core.validators.MaxValueValidator(132)])),
                ('psych_soc', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(118), django.core.validators.MaxValueValidator(132)])),
                ('cars', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(118), django.core.validators.MaxValueValidator(132)])),
                ('mcat_score', models.PositiveIntegerField(default=528, validators=[django.core.validators.MinValueValidator(472), django.core.validators.MaxValueValidator(528)])),
            ],
            options={
                'verbose_name_plural': 'MCAT',
            },
        ),
    ]
